version: '3.8'

services:
  simulacao-credito-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: simulacao-credito-api
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__DefaultConnection=Server=dbhackathon.database.windows.net,1433;Database=hack;User Id=hack;Password=Password123;Encrypt=True;TrustServerCertificate=False;
      - EventHub__ConnectionString=Endpoint=sb://eventhack.servicebus.windows.net/;SharedAccessKeyName=hack;SharedAccessKey=HeHeVaVayVkntO2FnjQcs2Ilh/4MUDo4y+AEhKp8z+g=;EntityPath=simulacoes
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - simulacao-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  simulacao-network:
    driver: bridge

volumes:
  simulacao-data:
